# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: en-US
title: Youngram House Journal
email: ian@iangreenleaf.com
description: >-
  Chronicling our homeowner journey
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
copyright: '<span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Youngram House Journal</span> © <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Ian Young</span>, released under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>'

# Build settings
markdown: kramdown
theme: jekyll-theme-so-simple
responsive_image:
  template: _includes/responsive-image.html
  base_path: assets/images
  output_path_format: assets/images/%{dirname}/resized/%{filename}-%{width}.%{extension}
  default_quality: 90
  sizes:
    - width: 480
      quality: 80
    - width: 800
    - width: 1200
  auto_rotate: false
  strip: false
  save_to_source: false
  cache: false
plugins:
  - jekyll-feed
  - jekyll-responsive-image

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
